### ISSUE TITLE
Open Native iOS App from Nativescript screen

### ISSUE THREAD

**Issue by LSmint** [NativeScript/sample-ios-embedded#9]
Is it possible to open a new screen of Native App view controller inside the NativeScript code?

**Comment by tdermendjiev** [comment]
Hello @LSmint ,
Would you be able to provide me an example of what you are trying to achieve so I can better understand the question? Thank you.

**Comment by tdermendjiev** [comment]
Hello @LSmint ,
If I understand correctly, you are trying to run Swift code in NS app. Currently the only way to achieve this is by creating a framework (or a [cocoapod](https://docs.nativescript.org/plugins/cocoapods)) and wrap it in a NativeScript plugin. Keep in mind that your Swift APIs have to be visible to the Objective-C runtime in order to access them from javascript. For more information see [here](https://developer.apple.com/documentation/swift#2984801).

**Comment by LSmint** [comment]
Hi @tdermendjiev,

These all links really helpful for me to understand more how it works! Thanks for your advice!
